version: '3.8'

services:
  app:
    build: .
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    command: npm start

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
    volumes:
      - .:/usr/src/app
    depends_on:
      - app
    command: npm test
